# Generated by Django 4.2.18 on 2026-03-28 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_question_questiontag_subjectroom_questionsubpart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.FloatField(
                        help_text="Mark obtained for this subpart (fraction 0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this tick has been factored into proficiency calculations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_subpart",
                    models.ForeignKey(
                        help_text="The question subpart that was answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="core.questionsubpart",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student whose answer resulted in this tick",
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="The SubjectRoom whose assignment produced this tick",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="core.subjectroom",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The submission this tick came from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "subject_room"],
                        name="edge_tick_student_de77c3_idx",
                    ),
                    models.Index(
                        fields=["is_acknowledged"], name="edge_tick_is_ackn_5f482f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="edge_tick_created_47a80d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectRoomQuestionMistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regression",
                    models.FloatField(
                        default=0.0,
                        help_text="Cumulative marks lost (absolute, not fraction) — higher = harder question for this class",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question for which incorrect answers are aggregated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_mistakes",
                        to="core.question",
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="The SubjectRoom whose students made the mistakes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_mistakes",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject_room", "question")},
            },
        ),
        migrations.CreateModel(
            name="SubjectRoomProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_tag",
                    models.ForeignKey(
                        help_text="The tag that this class-level proficiency is calculated in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjectroom_proficiencies",
                        to="core.questiontag",
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="The SubjectRoom for which aggregate proficiency is tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjectroom_proficiencies",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("question_tag", "subject_room")},
            },
        ),
        migrations.CreateModel(
            name="StudentProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.FloatField(
                        default=0.0,
                        help_text="Cumulative marks obtained across all ticks in this tag",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "tick_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of ticks this proficiency is calculated over",
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Average mark in this tag (total_marks / tick_count)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentile rank within this SubjectRoom and tag (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Final proficiency score: (0.7 × rate) + (0.3 × percentile)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_tag",
                    models.ForeignKey(
                        help_text="The tag that this proficiency is calculated in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_proficiencies",
                        to="core.questiontag",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student whose proficiency is tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="The SubjectRoom in which this proficiency applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_proficiencies",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_room", "question_tag"],
                        name="edge_studen_subject_ff809c_idx",
                    ),
                    models.Index(
                        fields=["student", "score"],
                        name="edge_studen_student_7921e8_idx",
                    ),
                ],
                "unique_together": {("student", "question_tag", "subject_room")},
            },
        ),
    ]
