# Generated by Django 4.2.30 on 2026-05-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_questionsubpart_variable_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("edge", "0001_tick_proficiency"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProficiencySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField(help_text="Snapshot of score at this point in time (0.0–1.0)")),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "question_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_snapshots",
                        to="core.questiontag",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_snapshots",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "question_tag", "subject_room", "recorded_at"],
                        name="edge_studen_student_a3e33a_idx",
                    )
                ],
            },
        ),
    ]
