# Generated by Django 4.2.30 on 2026-05-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_student_streak_and_remedial_fields"),
        ("edge", "0002_add_student_proficiency_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tick",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                help_text="The submission this tick came from. Null for SRS drill ticks.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticks",
                to="core.submission",
            ),
        ),
    ]
