"""
AI Analytics models for OpenShiksha

Implements smart analytics and insights:
- LearningGap: Per-student weakness detection at chapter level
- ClassInsight: Aggregated class-level insight for teachers
- PerformancePrediction: Heuristic exam-readiness forecast per subject

AI-Powered Content Recommendations:
- ContentRecommendation: What a student should practice next (and why)
- PracticePlan: A daily bundle of recommendations for a student

All analytics are computed asynchronously via Celery tasks and cached here
for fast API reads. The source of truth is always the Tick + StudentProficiency
data in edge/; these models are derived views.
"""

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

FRACTION_VALIDATOR = [MinValueValidator(0.0), MaxValueValidator(1.0)]


class GapSeverity(models.TextChoices):
    MILD = 'mild', 'Mild (score 40–50%)'
    MODERATE = 'moderate', 'Moderate (score 25–40%)'
    SEVERE = 'severe', 'Severe (score < 25%)'


class InsightType(models.TextChoices):
    STRUGGLING = 'struggling', 'Class Struggling (>40% below threshold)'
    AT_RISK = 'at_risk', 'At Risk (20–40% below threshold)'
    PROFICIENT = 'proficient', 'Class Proficient (<20% below threshold)'


class LearningGap(models.Model):
    """
    A detected weakness for a specific student in a specific chapter.

    Computed by scanning all Ticks for the student across questions in that
    chapter. Refreshed whenever new Ticks are acknowledged for the student.

    severity is derived from avg_score:
      severe:   avg_score < 0.25
      moderate: 0.25 <= avg_score < 0.40
      mild:     0.40 <= avg_score < 0.50
    """
    student = models.ForeignKey(
        'core.User',
        on_delete=models.CASCADE,
        related_name='learning_gaps',
        limit_choices_to={'role__in': ['student', 'open_student']},
    )
    chapter = models.ForeignKey(
        'core.Chapter',
        on_delete=models.CASCADE,
        related_name='learning_gaps',
    )
    subject_room = models.ForeignKey(
        'core.SubjectRoom',
        on_delete=models.CASCADE,
        related_name='learning_gaps',
        help_text='Context in which the gap was observed',
    )

    avg_score = models.FloatField(
        validators=FRACTION_VALIDATOR,
        help_text='Student average mark across all ticks in this chapter (0.0–1.0)',
    )
    severity = models.CharField(
        max_length=10,
        choices=GapSeverity.choices,
    )
    tick_count = models.PositiveIntegerField(
        help_text='Number of question-subpart ticks that contributed to this score',
    )

    is_resolved = models.BooleanField(
        default=False,
        help_text='Set True when avg_score rises >= 0.60 on a re-analysis',
    )
    detected_at = models.DateTimeField(auto_now_add=True)
    refreshed_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'ai_learning_gaps'
        unique_together = [['student', 'chapter', 'subject_room']]
        indexes = [
            models.Index(fields=['student', 'is_resolved']),
            models.Index(fields=['chapter', 'is_resolved']),
            models.Index(fields=['subject_room', 'severity']),
        ]

    def __str__(self):
        return (
            f'Gap: {self.student} | {self.chapter} | '
            f'{self.severity} ({self.avg_score:.0%})'
        )

    @staticmethod
    def severity_for_score(score: float) -> str:
        if score < 0.25:
            return GapSeverity.SEVERE
        if score < 0.40:
            return GapSeverity.MODERATE
        return GapSeverity.MILD


class ClassInsight(models.Model):
    """
    Aggregated performance insight for a teacher about their SubjectRoom on a Chapter.

    Generated by analysing all students' ticks in the subject_room for questions
    in the chapter. Refreshed after grading runs.

    insight_type:
      struggling: >40% of students below 50% average
      at_risk:    20–40% below threshold
      proficient: <20% below threshold
    """
    subject_room = models.ForeignKey(
        'core.SubjectRoom',
        on_delete=models.CASCADE,
        related_name='class_insights',
    )
    chapter = models.ForeignKey(
        'core.Chapter',
        on_delete=models.CASCADE,
        related_name='class_insights',
    )

    insight_type = models.CharField(max_length=15, choices=InsightType.choices)
    class_avg_score = models.FloatField(
        validators=FRACTION_VALIDATOR,
        help_text='Class average mark for this chapter (0.0–1.0)',
    )
    students_assessed = models.PositiveIntegerField(
        help_text='Number of students with at least 1 tick in this chapter',
    )
    students_struggling = models.PositiveIntegerField(
        help_text='Students with avg_score < 0.50 in this chapter',
    )
    pct_struggling = models.FloatField(
        validators=FRACTION_VALIDATOR,
        help_text='Fraction of assessed students who are struggling (0.0–1.0)',
    )

    generated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'ai_class_insights'
        unique_together = [['subject_room', 'chapter']]
        indexes = [
            models.Index(fields=['subject_room', 'insight_type']),
        ]

    def __str__(self):
        return (
            f'Insight: {self.subject_room} | {self.chapter} | '
            f'{self.insight_type} (avg {self.class_avg_score:.0%})'
        )

    @staticmethod
    def insight_type_for_pct(pct: float) -> str:
        if pct > 0.40:
            return InsightType.STRUGGLING
        if pct > 0.20:
            return InsightType.AT_RISK
        return InsightType.PROFICIENT


class PerformancePrediction(models.Model):
    """
    Heuristic exam-readiness forecast for a student in a subject.

    Algorithm:
    1. Collect all StudentProficiency scores for the student across all tags
       in questions within the subject (filtered by subject_room.subject).
    2. Apply recency weighting: ticks from last 30 days count double.
    3. Weighted average = predicted_score.
    4. Confidence = sigmoid(tick_count / 20) — low when data is sparse.

    predicted_score  < 0.40 → needs_attention
    0.40 <= score < 0.65 → developing
    0.65 <= score < 0.80 → on_track
    score >= 0.80       → exam_ready
    """

    class ReadinessLevel(models.TextChoices):
        NEEDS_ATTENTION = 'needs_attention', 'Needs Attention'
        DEVELOPING = 'developing', 'Developing'
        ON_TRACK = 'on_track', 'On Track'
        EXAM_READY = 'exam_ready', 'Exam Ready'

    student = models.ForeignKey(
        'core.User',
        on_delete=models.CASCADE,
        related_name='performance_predictions',
        limit_choices_to={'role__in': ['student', 'open_student']},
    )
    subject_room = models.ForeignKey(
        'core.SubjectRoom',
        on_delete=models.CASCADE,
        related_name='performance_predictions',
    )

    predicted_score = models.FloatField(
        validators=FRACTION_VALIDATOR,
        help_text='Predicted performance score (0.0–1.0)',
    )
    confidence = models.FloatField(
        validators=FRACTION_VALIDATOR,
        help_text='Confidence in the prediction — low when tick data is sparse',
    )
    readiness_level = models.CharField(
        max_length=20,
        choices=ReadinessLevel.choices,
    )
    tick_count = models.PositiveIntegerField(
        help_text='Total ticks used to compute this prediction',
    )
    factors = models.JSONField(
        default=dict,
        help_text=(
            'Top contributing factors: '
            '{"strong_chapters": [...], "weak_chapters": [...], '
            '"recent_trend": "improving|declining|stable"}'
        ),
    )

    generated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'ai_performance_predictions'
        unique_together = [['student', 'subject_room']]
        indexes = [
            models.Index(fields=['student', 'readiness_level']),
            models.Index(fields=['subject_room', 'readiness_level']),
        ]

    def __str__(self):
        return (
            f'Prediction: {self.student} | {self.subject_room} | '
            f'{self.readiness_level} ({self.predicted_score:.0%}, '
            f'confidence {self.confidence:.0%})'
        )

    @staticmethod
    def readiness_for_score(score: float) -> str:
        if score >= 0.80:
            return PerformancePrediction.ReadinessLevel.EXAM_READY
        if score >= 0.65:
            return PerformancePrediction.ReadinessLevel.ON_TRACK
        if score >= 0.40:
            return PerformancePrediction.ReadinessLevel.DEVELOPING
        return PerformancePrediction.ReadinessLevel.NEEDS_ATTENTION


# ─────────────────────────────────────────────────────────────────────────────
# Content Recommendations
# ─────────────────────────────────────────────────────────────────────────────

class RecommendationReason(models.TextChoices):
    SEVERE_GAP = 'severe_gap', 'Severe Gap — urgent remediation needed'
    MODERATE_GAP = 'moderate_gap', 'Moderate Gap — needs more practice'
    MILD_GAP = 'mild_gap', 'Mild Gap — a few more attempts recommended'
    SPACED_REVIEW = 'spaced_review', 'Spaced Review — reinforce resolved gap'
    NEXT_TOPIC = 'next_topic', 'Next Topic — ready to progress'


class RecommendationPriority(models.IntegerChoices):
    URGENT = 1, 'Urgent'
    HIGH = 2, 'High'
    MEDIUM = 3, 'Medium'
    LOW = 4, 'Low'


class ContentRecommendation(models.Model):
    """
    A single "practice this next" recommendation for a student.

    Generated by scanning LearningGap and PerformancePrediction data.

    Priority rules (lower number = higher priority):
      1 (urgent)  — severe active gap
      2 (high)    — moderate active gap  OR  spaced_review of recently resolved gap
      3 (medium)  — mild active gap
      4 (low)     — next_topic progression (student ready to advance)

    is_actioned becomes True when the student opens or submits the problem set.
    Stale recommendations (superseded by re-analysis) are soft-deleted via is_active=False.
    """
    student = models.ForeignKey(
        'core.User',
        on_delete=models.CASCADE,
        related_name='content_recommendations',
        limit_choices_to={'role__in': ['student', 'open_student']},
    )
    subject_room = models.ForeignKey(
        'core.SubjectRoom',
        on_delete=models.CASCADE,
        related_name='content_recommendations',
    )
    chapter = models.ForeignKey(
        'core.Chapter',
        on_delete=models.CASCADE,
        related_name='content_recommendations',
    )
    problem_set = models.ForeignKey(
        'core.ProblemSet',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='content_recommendations',
        help_text='Specific problem set to attempt (null = any set in the chapter)',
    )

    reason = models.CharField(max_length=20, choices=RecommendationReason.choices)
    priority = models.PositiveSmallIntegerField(
        choices=RecommendationPriority.choices,
        help_text='Lower = more urgent',
    )

    # Snapshot of the score that triggered this recommendation (for audit / display)
    score_snapshot = models.FloatField(
        null=True,
        blank=True,
        validators=FRACTION_VALIDATOR,
        help_text='Student avg score in this chapter when the recommendation was generated',
    )

    is_actioned = models.BooleanField(
        default=False,
        help_text='True once the student has opened or submitted the recommended problem set',
    )
    is_active = models.BooleanField(
        default=True,
        help_text='False when superseded by a newer analysis run',
    )

    generated_at = models.DateTimeField(auto_now_add=True)
    actioned_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ai_content_recommendations'
        # Only one active recommendation per student × chapter × subject_room
        unique_together = [['student', 'chapter', 'subject_room']]
        indexes = [
            models.Index(fields=['student', 'is_active', 'priority']),
            models.Index(fields=['subject_room', 'is_active']),
        ]

    def __str__(self):
        return (
            f'Rec: {self.student} | {self.chapter} | '
            f'{self.get_reason_display()} (p{self.priority})'
        )

    @staticmethod
    def priority_for_reason(reason: str) -> int:
        mapping = {
            RecommendationReason.SEVERE_GAP: RecommendationPriority.URGENT,
            RecommendationReason.MODERATE_GAP: RecommendationPriority.HIGH,
            RecommendationReason.SPACED_REVIEW: RecommendationPriority.HIGH,
            RecommendationReason.MILD_GAP: RecommendationPriority.MEDIUM,
            RecommendationReason.NEXT_TOPIC: RecommendationPriority.LOW,
        }
        return mapping.get(reason, RecommendationPriority.MEDIUM)


class PracticePlan(models.Model):
    """
    A daily practice plan for a student in a SubjectRoom.

    Bundles the top N active ContentRecommendations into a digestible plan.
    One plan per student × subject_room × date.

    estimated_minutes = sum of estimated_minutes for linked problem sets
    (defaults to 10 min per recommendation if problem set has no estimate).
    """
    student = models.ForeignKey(
        'core.User',
        on_delete=models.CASCADE,
        related_name='practice_plans',
        limit_choices_to={'role__in': ['student', 'open_student']},
    )
    subject_room = models.ForeignKey(
        'core.SubjectRoom',
        on_delete=models.CASCADE,
        related_name='practice_plans',
    )
    recommendations = models.ManyToManyField(
        ContentRecommendation,
        related_name='practice_plans',
        blank=True,
    )
    plan_date = models.DateField(help_text='The day this plan is intended for')
    estimated_minutes = models.PositiveIntegerField(
        default=0,
        help_text='Total estimated practice time in minutes',
    )
    is_completed = models.BooleanField(
        default=False,
        help_text='True when the student has actioned all recommendations in the plan',
    )
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'ai_practice_plans'
        unique_together = [['student', 'subject_room', 'plan_date']]
        indexes = [
            models.Index(fields=['student', 'plan_date']),
            models.Index(fields=['subject_room', 'plan_date']),
        ]

    def __str__(self):
        return (
            f'Plan: {self.student} | {self.subject_room} | '
            f'{self.plan_date} (~{self.estimated_minutes}min)'
        )
