apiVersion: v1
kind: ConfigMap
metadata:
  name: openshiksha-config
data:
  ALLOWED_HOSTS: openshiksha.org,www.openshiksha.org,backend
  CORS_ALLOWED_ORIGINS: https://openshiksha.org,https://www.openshiksha.org
  CSRF_TRUSTED_ORIGINS: https://openshiksha.org,https://www.openshiksha.org
