[pytest]
DJANGO_SETTINGS_MODULE = openshiksha.settings.test
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=openshiksha --cov-report=term-missing --cov-report=xml --cov-fail-under=90
