# Generated by Django 4.2.18 on 2026-03-29 02:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_question_questiontag_subjectroom_questionsubpart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformancePrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "predicted_score",
                    models.FloatField(
                        help_text="Predicted performance score (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence in the prediction — low when tick data is sparse",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "readiness_level",
                    models.CharField(
                        choices=[
                            ("needs_attention", "Needs Attention"),
                            ("developing", "Developing"),
                            ("on_track", "On Track"),
                            ("exam_ready", "Exam Ready"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tick_count", models.PositiveIntegerField(help_text="Total ticks used to compute this prediction")),
                (
                    "factors",
                    models.JSONField(
                        default=dict,
                        help_text='Top contributing factors: {"strong_chapters": [...], "weak_chapters": [...], "recent_trend": "improving|declining|stable"}',
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_predictions",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_performance_predictions",
                "indexes": [
                    models.Index(fields=["student", "readiness_level"], name="ai_performa_student_81f41c_idx"),
                    models.Index(fields=["subject_room", "readiness_level"], name="ai_performa_subject_28876f_idx"),
                ],
                "unique_together": {("student", "subject_room")},
            },
        ),
        migrations.CreateModel(
            name="LearningGap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "avg_score",
                    models.FloatField(
                        help_text="Student average mark across all ticks in this chapter (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild (score 40–50%)"),
                            ("moderate", "Moderate (score 25–40%)"),
                            ("severe", "Severe (score < 25%)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tick_count",
                    models.PositiveIntegerField(
                        help_text="Number of question-subpart ticks that contributed to this score"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Set True when avg_score rises >= 0.60 on a re-analysis"
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="learning_gaps", to="core.chapter"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_gaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="Context in which the gap was observed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_gaps",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_learning_gaps",
                "indexes": [
                    models.Index(fields=["student", "is_resolved"], name="ai_learning_student_c254ba_idx"),
                    models.Index(fields=["chapter", "is_resolved"], name="ai_learning_chapter_361bf1_idx"),
                    models.Index(fields=["subject_room", "severity"], name="ai_learning_subject_645c32_idx"),
                ],
                "unique_together": {("student", "chapter", "subject_room")},
            },
        ),
        migrations.CreateModel(
            name="ClassInsight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("struggling", "Class Struggling (>40% below threshold)"),
                            ("at_risk", "At Risk (20–40% below threshold)"),
                            ("proficient", "Class Proficient (<20% below threshold)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "class_avg_score",
                    models.FloatField(
                        help_text="Class average mark for this chapter (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "students_assessed",
                    models.PositiveIntegerField(help_text="Number of students with at least 1 tick in this chapter"),
                ),
                (
                    "students_struggling",
                    models.PositiveIntegerField(help_text="Students with avg_score < 0.50 in this chapter"),
                ),
                (
                    "pct_struggling",
                    models.FloatField(
                        help_text="Fraction of assessed students who are struggling (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="class_insights", to="core.chapter"
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_insights",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_class_insights",
                "indexes": [
                    models.Index(fields=["subject_room", "insight_type"], name="ai_class_in_subject_900486_idx")
                ],
                "unique_together": {("subject_room", "chapter")},
            },
        ),
    ]
