# Generated by Django 4.2.18 on 2026-03-30 03:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_question_questiontag_subjectroom_questionsubpart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("severe_gap", "Severe Gap — urgent remediation needed"),
                            ("moderate_gap", "Moderate Gap — needs more practice"),
                            ("mild_gap", "Mild Gap — a few more attempts recommended"),
                            ("spaced_review", "Spaced Review — reinforce resolved gap"),
                            ("next_topic", "Next Topic — ready to progress"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Urgent"), (2, "High"), (3, "Medium"), (4, "Low")],
                        help_text="Lower = more urgent",
                    ),
                ),
                (
                    "score_snapshot",
                    models.FloatField(
                        blank=True,
                        help_text="Student avg score in this chapter when the recommendation was generated",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "is_actioned",
                    models.BooleanField(
                        default=False,
                        help_text="True once the student has opened or submitted the recommended problem set",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False when superseded by a newer analysis run",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_recommendations",
                        to="core.chapter",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific problem set to attempt (null = any set in the chapter)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_recommendations",
                        to="core.problemset",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_recommendations",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_content_recommendations",
            },
        ),
        migrations.CreateModel(
            name="PracticePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_date",
                    models.DateField(help_text="The day this plan is intended for"),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total estimated practice time in minutes"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="True when the student has actioned all recommendations in the plan",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practice_plans",
                        to="ai.contentrecommendation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_plans",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_practice_plans",
                "indexes": [
                    models.Index(
                        fields=["student", "plan_date"],
                        name="ai_practice_student_6bdfc8_idx",
                    ),
                    models.Index(
                        fields=["subject_room", "plan_date"],
                        name="ai_practice_subject_d1b402_idx",
                    ),
                ],
                "unique_together": {("student", "subject_room", "plan_date")},
            },
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["student", "is_active", "priority"],
                name="ai_content__student_31908a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["subject_room", "is_active"],
                name="ai_content__subject_74a34b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentrecommendation",
            unique_together={("student", "chapter", "subject_room")},
        ),
    ]
