# Generated by Django 4.2.18 on 2026-03-31 02:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_question_questiontag_subjectroom_questionsubpart_and_more"),
        ("ai", "0002_content_recommendations_practice_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Relative difficulty 0.1–5.0; affects spaced repetition interval scaling",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_nodes",
                        to="core.chapter",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chapters that should be mastered before this one",
                        related_name="unlocks",
                        to="ai.knowledgenode",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_nodes",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_nodes",
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("stale", "Stale (regenerated)"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("completed_steps", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_learning_paths",
            },
        ),
        migrations.CreateModel(
            name="StudentMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_score",
                    models.FloatField(
                        default=0.0,
                        help_text="EWMA of scores across all attempts (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown (not attempted)"),
                            ("novice", "Novice (0–39%)"),
                            ("developing", "Developing (40–59%)"),
                            ("proficient", "Proficient (60–79%)"),
                            ("mastered", "Mastered (80%+)"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of practice attempts contributing to this score",
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the student last practiced this chapter",
                        null=True,
                    ),
                ),
                (
                    "first_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the student first attempted this chapter",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "knowledge_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="ai.knowledgenode",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_student_mastery",
                "indexes": [
                    models.Index(
                        fields=["student", "mastery_level"],
                        name="ai_student__student_196744_idx",
                    ),
                    models.Index(
                        fields=["knowledge_node", "mastery_level"],
                        name="ai_student__knowled_9f3f86_idx",
                    ),
                ],
                "unique_together": {("student", "knowledge_node")},
            },
        ),
        migrations.CreateModel(
            name="SpacedRepetitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        default=1, help_text="Days until next review"
                    ),
                ),
                (
                    "easiness_factor",
                    models.FloatField(
                        default=2.5,
                        help_text="SM-2 easiness factor — controls interval growth rate",
                        validators=[
                            django.core.validators.MinValueValidator(1.3),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "repetitions",
                    models.PositiveIntegerField(
                        default=0, help_text="Consecutive successful review count"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        help_text="Date on which this chapter is scheduled for review"
                    ),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "knowledge_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_entries",
                        to="ai.knowledgenode",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_spaced_repetition_entries",
                "indexes": [
                    models.Index(
                        fields=["student", "next_review_date"],
                        name="ai_spaced_r_student_f5b312_idx",
                    ),
                    models.Index(
                        fields=["knowledge_node", "next_review_date"],
                        name="ai_spaced_r_knowled_96b653_idx",
                    ),
                ],
                "unique_together": {("student", "knowledge_node")},
            },
        ),
        migrations.CreateModel(
            name="LearningPathStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="1-indexed order in the learning path"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "is_review",
                    models.BooleanField(
                        default=False,
                        help_text="True when inserted by spaced-repetition scheduler for review",
                    ),
                ),
                (
                    "score_when_completed",
                    models.FloatField(
                        blank=True,
                        help_text="Score the student achieved when they completed this step",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "knowledge_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_steps",
                        to="ai.knowledgenode",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="ai.learningpath",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="Suggested problem set for this step; null = student chooses freely",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="path_steps",
                        to="core.problemset",
                    ),
                ),
            ],
            options={
                "db_table": "ai_learning_path_steps",
                "indexes": [
                    models.Index(
                        fields=["learning_path", "status"],
                        name="ai_learning_learnin_575a7d_idx",
                    ),
                    models.Index(
                        fields=["knowledge_node", "status"],
                        name="ai_learning_knowled_7514ea_idx",
                    ),
                ],
                "unique_together": {("learning_path", "position")},
            },
        ),
        migrations.AddIndex(
            model_name="learningpath",
            index=models.Index(
                fields=["student", "status"], name="ai_learning_student_dc5b79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningpath",
            index=models.Index(
                fields=["subject_room", "status"], name="ai_learning_subject_a00d31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(
                fields=["subject", "is_active"], name="ai_knowledg_subject_e133f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgenode",
            unique_together={("subject", "chapter")},
        ),
    ]
