# Generated by Django 4.2.30 on 2026-05-27 03:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fix_classroom_invite_code_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0003_adaptive_learning_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubpartExplanation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "student_answer",
                    models.JSONField(help_text="The answer the student submitted (raw value, pre-croupier-reversal)."),
                ),
                ("is_correct", models.BooleanField(help_text="Whether the student's answer was graded as correct.")),
                (
                    "explanation_text",
                    models.TextField(help_text="AI-generated plain-language explanation (2–5 sentences)."),
                ),
                (
                    "language",
                    models.CharField(choices=[("en", "English"), ("hi", "Hindi")], default="en", max_length=5),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        help_text="Grade level used to calibrate explanation complexity.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="claude-sonnet-4-6",
                        help_text="LLM model ID that generated this explanation.",
                        max_length=60,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, help_text="Prompt tokens consumed (for cost tracking)."),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, help_text="Completion tokens produced (for cost tracking)."),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_subpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="core.questionsubpart",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subpart_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for SRS drill explanations not tied to a formal submission.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "db_table": "ai_subpart_explanations",
                "indexes": [
                    models.Index(fields=["submission"], name="ai_subpart__submiss_145bb6_idx"),
                    models.Index(fields=["student", "generated_at"], name="ai_subpart__student_3d0bdb_idx"),
                ],
                "unique_together": {("student", "question_subpart", "submission")},
            },
        ),
    ]
