# Generated by Django 4.2.30 on 2026-05-28 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fix_classroom_invite_code_fk"),
        ("ai", "0004_natural_language_explanations"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyClassReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField(help_text="Monday of the reporting week (local date).")),
                ("week_end", models.DateField(help_text="Sunday of the reporting week (week_start + 6 days).")),
                ("summary_text", models.TextField(help_text="AI-generated plain-language narrative for the teacher.")),
                (
                    "total_students",
                    models.PositiveIntegerField(default=0, help_text="Students enrolled in the subject room."),
                ),
                (
                    "active_students",
                    models.PositiveIntegerField(
                        default=0, help_text="Students with at least one tick during the week."
                    ),
                ),
                (
                    "ticks_recorded",
                    models.PositiveIntegerField(
                        default=0, help_text="Total question-subpart ticks recorded during the week."
                    ),
                ),
                (
                    "class_avg_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Mean tick mark across the week (0.0–1.0).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "struggling_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Weakest chapters this week: [{"chapter_id", "chapter_name", "avg_score", "tick_count"}].',
                    ),
                ),
                (
                    "strong_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Strongest chapters this week: [{"chapter_id", "chapter_name", "avg_score", "tick_count"}].',
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="stub", help_text="LLM model ID that generated the narrative.", max_length=60
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_weekly_class_reports",
                "ordering": ["-week_start"],
                "indexes": [models.Index(fields=["subject_room", "week_start"], name="ai_weekly_c_subject_45d4fb_idx")],
                "unique_together": {("subject_room", "week_start")},
            },
        ),
    ]
