# Generated by Django 4.2.30 on 2026-05-29 05:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_questionsubpart_solution_hint_text"),
        ("ai", "0005_weeklyclassreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMisconception",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_answer", models.JSONField(help_text="The (incorrect) answer the student submitted.")),
                (
                    "misconception_label",
                    models.CharField(
                        help_text="Short label for the underlying misconception (e.g. 'sign error on subtraction').",
                        max_length=120,
                    ),
                ),
                (
                    "diagnosis_text",
                    models.TextField(
                        help_text="Plain-language explanation of the faulty reasoning that led to the wrong answer."
                    ),
                ),
                (
                    "remediation_tip",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Concrete, actionable suggestion for what the student should review or practise.",
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("model_used", models.CharField(default="stub", max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("detected_at", models.DateTimeField(auto_now=True)),
                (
                    "question_subpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconceptions",
                        to="core.questionsubpart",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for SRS drill diagnoses not tied to a formal submission.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconceptions",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "db_table": "ai_student_misconceptions",
                "indexes": [
                    models.Index(fields=["student", "detected_at"], name="ai_student__student_21bbe6_idx"),
                    models.Index(fields=["question_subpart"], name="ai_student__questio_2ae8b5_idx"),
                ],
                "unique_together": {("student", "question_subpart", "submission")},
            },
        ),
        migrations.CreateModel(
            name="HintSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hints",
                    models.JSONField(
                        default=list, help_text='Ordered nudge→strong hints: [{"level": 1, "text": "..."}, ...].'
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Grade level used to calibrate hint language.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "model_used",
                    models.CharField(default="stub", help_text="LLM model ID that generated the hints.", max_length=60),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_subpart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_sequence",
                        to="core.questionsubpart",
                    ),
                ),
            ],
            options={
                "db_table": "ai_hint_sequences",
                "indexes": [models.Index(fields=["question_subpart"], name="ai_hint_seq_questio_55a3bf_idx")],
            },
        ),
    ]
