# Generated by Django 4.2.30 on 2026-05-30 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0006_studentmisconception_hintsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProgressSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField(help_text="Monday of the reporting week (local date).")),
                ("week_end", models.DateField(help_text="Sunday of the reporting week (week_start + 6 days).")),
                (
                    "summary_text",
                    models.TextField(help_text="AI-generated plain-language weekly narrative for the parent."),
                ),
                (
                    "language",
                    models.CharField(choices=[("en", "English"), ("hi", "Hindi")], default="en", max_length=5),
                ),
                (
                    "ticks_recorded",
                    models.PositiveIntegerField(default=0, help_text="Total ticks the child recorded during the week."),
                ),
                (
                    "active_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Distinct calendar days the child practised during the week."
                    ),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Child's mean tick mark across the week (0.0–1.0).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "score_delta",
                    models.FloatField(
                        default=0.0,
                        help_text="Change in avg_score vs the prior week (positive = improving).",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weak_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Weakest chapters this week: [{"chapter_id", "chapter_name", "avg_score", "tick_count"}].',
                    ),
                ),
                (
                    "strong_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Strongest chapters this week: [{"chapter_id", "chapter_name", "avg_score", "tick_count"}].',
                    ),
                ),
                (
                    "home_activities",
                    models.JSONField(
                        default=list,
                        help_text='Suggested at-home activities the parent can do with the child: [{"title", "description", "chapter_name"}].',
                    ),
                ),
                (
                    "alerts",
                    models.JSONField(
                        default=list,
                        help_text='Parent alerts worth attention: [{"severity": "info|attention|urgent", "label", "detail"}].',
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="stub", help_text="LLM model ID that generated the narrative.", max_length=60
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_summaries_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_parent_progress_summaries",
                "ordering": ["-week_start"],
                "indexes": [
                    models.Index(fields=["parent", "week_start"], name="ai_parent_p_parent__92d012_idx"),
                    models.Index(fields=["child", "week_start"], name="ai_parent_p_child_i_30851e_idx"),
                ],
                "unique_together": {("parent", "child", "week_start")},
            },
        ),
    ]
