# Generated by Django 4.2.30 on 2026-05-31 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_email_reminders_opt_out_assignmentreminder"),
        ("ai", "0007_parent_progress_summaries"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassMisconceptionCluster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "misconception_label",
                    models.CharField(
                        help_text="The shared, short misconception label (e.g. 'sign error on subtraction').",
                        max_length=120,
                    ),
                ),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Distinct students in the room exhibiting this misconception in the window.",
                    ),
                ),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total StudentMisconception rows matched (one student may contribute several).",
                    ),
                ),
                (
                    "sample_diagnosis",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A representative diagnosis line copied from one of the underlying records.",
                    ),
                ),
                (
                    "sample_remediation_tip",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A representative remediation tip copied from one of the underlying records.",
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(help_text="Start of the lookback window used to build this cluster."),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        help_text="Most recent detected_at across the underlying StudentMisconception rows."
                    ),
                ),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconception_clusters",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_class_misconception_clusters",
                "ordering": ["-student_count", "-last_seen"],
                "indexes": [
                    models.Index(fields=["subject_room", "-student_count"], name="ai_class_mi_subject_ff0b55_idx")
                ],
                "unique_together": {("subject_room", "misconception_label")},
            },
        ),
    ]
