# Generated by Django 4.2.30 on 2026-06-01 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_email_reminders_opt_out_assignmentreminder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0008_classmisconceptioncluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Generating"),
                            ("ready", "Ready for review"),
                            ("approved", "Approved"),
                            ("dismissed", "Dismissed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Suggested assignment title (teacher may edit on approval).",
                        max_length=255,
                    ),
                ),
                (
                    "rationale_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated plain-language explanation of why these questions were chosen.",
                    ),
                ),
                (
                    "target_difficulty",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Difficulty the teacher asked the draft to centre on (1=easiest, 5=hardest).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "requested_size",
                    models.PositiveSmallIntegerField(default=8, help_text="Number of questions the teacher asked for."),
                ),
                (
                    "target_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Weak chapters the draft targets, weakest first: [{"chapter_id", "chapter_name", "avg_score", "tick_count"}].',
                    ),
                ),
                (
                    "selected_questions",
                    models.JSONField(
                        default=list,
                        help_text='Chosen questions in order: [{"question_id", "chapter_id", "chapter_name", "difficulty", "question_type", "preview", "reason"}].',
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Sum of estimated time across selected questions."
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="stub", help_text="LLM model ID that generated the rationale.", max_length=60
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "error_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Populated when status=failed (e.g. no weak chapters / no questions in bank).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assignment created when the teacher approved this draft.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="core.assignment",
                    ),
                ),
                (
                    "approved_problem_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProblemSet created when the teacher approved this draft.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="core.problemset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_drafts_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_drafts",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assignment_drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["subject_room", "status"], name="ai_assignme_subject_3b287f_idx"),
                    models.Index(fields=["requested_by", "-created_at"], name="ai_assignme_request_599d17_idx"),
                ],
            },
        ),
    ]
