# Generated by Django 4.2.30 on 2026-06-02 02:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_alter_question_question_type"),
        ("ai", "0009_assignmentdraft"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenResponseRubric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "max_marks",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Total marks an answer can earn.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "model_answer",
                    models.TextField(
                        blank=True, default="", help_text="The ideal/expected answer the AI grades responses against."
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Optional analytic rubric points: [{"label": "...", "description": "...", "marks": 2}]. Marks should sum to max_marks; the grader awards per-point credit.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="open_response_rubrics_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subpart",
                    models.OneToOneField(
                        help_text="The short-answer subpart this rubric grades.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_response_rubric",
                        to="core.questionsubpart",
                    ),
                ),
            ],
            options={
                "db_table": "ai_open_response_rubrics",
                "indexes": [models.Index(fields=["subpart"], name="ai_open_res_subpart_c002f0_idx")],
            },
        ),
        migrations.CreateModel(
            name="OpenResponseGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response_text", models.TextField(help_text="The student's free-text answer being graded.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting AI grading"),
                            ("ai_graded", "AI-graded, awaiting teacher review"),
                            ("reviewed", "Teacher-reviewed (final)"),
                            ("failed", "Grading failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "max_marks",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Snapshot of the rubric's max marks at grading time."
                    ),
                ),
                (
                    "suggested_score",
                    models.FloatField(
                        blank=True, help_text="AI-suggested marks (0..max_marks). Null until graded.", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, default="", help_text="AI plain-language feedback for the student."),
                ),
                (
                    "criterion_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Per-criterion award: [{"label", "awarded", "max", "comment"}].',
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence in its suggested score (0..1).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        blank=True,
                        help_text="Teacher's final marks. Set on review; overrides suggested_score.",
                        null=True,
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, default="", help_text="Optional teacher note added during review."),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("model_used", models.CharField(default="stub", max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="open_response_grades",
                        to="core.assignment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="open_response_grades_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_response_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="Room this response belongs to — scopes teacher ownership.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_response_grades",
                        to="core.subjectroom",
                    ),
                ),
                (
                    "subpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_response_grades",
                        to="core.questionsubpart",
                    ),
                ),
            ],
            options={
                "db_table": "ai_open_response_grades",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["subject_room", "status"], name="ai_open_res_subject_2881a1_idx"),
                    models.Index(fields=["student", "-created_at"], name="ai_open_res_student_a19c26_idx"),
                    models.Index(fields=["subpart", "student"], name="ai_open_res_subpart_30b691_idx"),
                ],
            },
        ),
    ]
