# Generated by Django 4.2.30 on 2026-06-03 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0017_questionsubpart_interactive_html_and_more"),
        ("ai", "0010_openresponserubric_openresponsegrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open (needs attention)"),
                            ("acknowledged", "Acknowledged by teacher"),
                            ("dismissed", "Dismissed by teacher"),
                            ("resolved", "Resolved (student recovered)"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1–5, higher = more urgent. Derived from gap severity and breadth.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild (score 40–50%)"),
                            ("moderate", "Moderate (score 25–40%)"),
                            ("severe", "Severe (score < 25%)"),
                        ],
                        help_text="Worst gap severity contributing to this suggestion.",
                        max_length=10,
                    ),
                ),
                (
                    "strategy_text",
                    models.TextField(help_text="AI-generated plain-language intervention plan for the teacher."),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Mean of the student's open-gap chapter scores (0.0–1.0).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "gap_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of open learning gaps this student has in the room."
                    ),
                ),
                (
                    "focus_chapters",
                    models.JSONField(
                        default=list,
                        help_text='Weakest chapters: [{"chapter_id", "chapter_name", "avg_score", "severity"}].',
                    ),
                ),
                (
                    "misconception_labels",
                    models.JSONField(default=list, help_text='Most common misconceptions: [{"label", "count"}].'),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("model_used", models.CharField(default="stub", max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_suggestions",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_intervention_suggestions",
                "ordering": ["-priority", "avg_score"],
                "indexes": [
                    models.Index(fields=["subject_room", "status", "-priority"], name="ai_interven_subject_f3540f_idx"),
                    models.Index(fields=["student", "status"], name="ai_interven_student_03cd46_idx"),
                ],
                "unique_together": {("subject_room", "student")},
            },
        ),
    ]
