# Generated by Django 4.2.30 on 2026-06-04 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_questionsubpart_interactive_html_and_more"),
        ("ai", "0011_interventionsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionDifficultyCalibration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Distinct students who attempted this subpart in the room."
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total ticks (attempts) the calibration was computed over."
                    ),
                ),
                (
                    "facility_index",
                    models.FloatField(
                        default=0.0,
                        help_text="Mean mark across attempts (0.0–1.0). High = easy, low = hard.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "discrimination_index",
                    models.FloatField(
                        blank=True,
                        help_text="Top-third facility minus bottom-third facility (-1.0–1.0). Null when too few students to compute.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "empirical_difficulty",
                    models.PositiveSmallIntegerField(
                        help_text="Difficulty (1=easiest, 5=hardest) implied by the facility index.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "declared_difficulty",
                    models.PositiveSmallIntegerField(
                        help_text="Snapshot of the authored Question.difficulty at calibration time.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("ok", "Well-calibrated"),
                            ("mislabeled", "Difficulty label mismatch"),
                            ("too_easy", "Too easy (low information)"),
                            ("too_hard", "Too hard (possibly unclear)"),
                            ("low_discrimination", "Low discrimination (possibly mis-keyed)"),
                        ],
                        default="ok",
                        help_text="Primary quality verdict for the item (priority-resolved).",
                        max_length=20,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "question_subpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_calibrations",
                        to="core.questionsubpart",
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_calibrations",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "db_table": "ai_question_difficulty_calibrations",
                "ordering": ["flag", "-sample_size"],
                "indexes": [
                    models.Index(fields=["subject_room", "flag"], name="ai_question_subject_282294_idx"),
                    models.Index(fields=["subject_room", "-sample_size"], name="ai_question_subject_f588e5_idx"),
                ],
                "unique_together": {("subject_room", "question_subpart")},
            },
        ),
    ]
