# Generated by Django 4.2.30 on 2026-06-05 02:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0017_questionsubpart_interactive_html_and_more"),
        ("ai", "0012_questiondifficultycalibration"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short label derived from the student's first message.",
                        max_length=120,
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Grade level used to calibrate the tutor's language.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "language",
                    models.CharField(choices=[("en", "English"), ("hi", "Hindi")], default="en", max_length=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_subpart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional anchor — the question the student is asking about.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutor_conversations",
                        to="core.questionsubpart",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_tutor_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("student", "Student"), ("tutor", "Tutor")], max_length=10)),
                ("content", models.TextField()),
                ("model_used", models.CharField(blank=True, default="", max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="ai.tutorconversation"
                    ),
                ),
            ],
            options={
                "db_table": "ai_tutor_messages",
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["conversation", "created_at"], name="ai_tutor_me_convers_548632_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="tutorconversation",
            index=models.Index(fields=["student", "-updated_at"], name="ai_tutor_co_student_f70da7_idx"),
        ),
        migrations.AddIndex(
            model_name="tutorconversation",
            index=models.Index(fields=["question_subpart"], name="ai_tutor_co_questio_a632e8_idx"),
        ),
    ]
