# Generated by Django 4.2.30 on 2026-05-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquirer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Contact person's name", max_length=255)),
                ("school", models.CharField(help_text="School or organization name", max_length=255)),
                ("email", models.EmailField(help_text="Contact email address", max_length=254)),
                ("phone", models.CharField(blank=True, default="", help_text="Contact phone number", max_length=15)),
                ("message", models.TextField(blank=True, default="", help_text="Optional message from the enquirer")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
