#!/usr/bin/env node
/**
 * `npm run widget:new <kind>` — scaffolds a new Interactive Widgets
 * Framework kind from a tiny template (IW-8-early).
 *
 * Compounding goal of the initiative: **a new widget kind costs one
 * folder + one registry entry**. Without the scaffolder, "one folder +
 * one entry" still means a contributor has to copy the `_hello` widget,
 * rename three identifiers, remember the JSON-Schema field shape, and
 * patch `registry.ts` in two places. This script makes it a single
 * command — and verifies the kind/slug, refuses duplicates, and prints
 * the one remaining manual step (the server-side `KNOWN_WIDGET_KINDS`
 * mirror).
 *
 * Usage:
 *     npm run widget:new number-line
 *     npm run widget:new -- color-picker
 *
 * The double-dash form is needed when npm would otherwise eat the kind
 * argument as an npm flag.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { kindToIdentifier, patchRegistry, validateKind } from './create-widget-utils.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const WIDGETS_DIR = join(ROOT, 'src', 'widgets');
const REGISTRY_PATH = join(WIDGETS_DIR, 'registry.ts');

function widgetIndexTemplate(kind, ident) {
  return `/**
 * \`${kind}\` widget — generated by \`npm run widget:new ${kind}\`.
 *
 * See \`docs/widgets/anatomy.md\` for the full SDK reference. The render
 * function below runs **inside the sandboxed iframe** — no captured
 * closures, no app-bundle imports.
 */

import { defineWidget } from '../_sdk/defineWidget';
import paramsSchema from './params.schema.json';

interface ${ident.charAt(0).toUpperCase() + ident.slice(1)}Config {
  /** TODO: declare typed config fields here, mirroring params.schema.json. */
  label?: string;
}

export default defineWidget({
  kind: '${kind}',
  version: 1,
  meta: {
    title: '${kind} widget',
    description: 'TODO: one-paragraph description for the teacher gallery.',
    answerProducing: false,
  },
  paramsSchema,
  render: (ctx) => {
    const cfg = ctx.config as ${ident.charAt(0).toUpperCase() + ident.slice(1)}Config;
    const label = typeof cfg.label === 'string' ? cfg.label : '${kind}';

    const p = document.createElement('p');
    p.textContent = 'Hello from ' + label + '!';
    p.style.margin = '0';
    ctx.mount.appendChild(p);
  },
});
`;
}

function paramsSchemaTemplate(kind) {
  return (
    JSON.stringify(
      {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        $id: `openshiksha:widget:${kind}/v1`,
        title: `${kind} widget params`,
        description: 'Per-question configuration for the widget.',
        type: 'object',
        additionalProperties: false,
        properties: {
          label: {
            type: 'string',
            description: 'TODO: replace with real config fields.',
            default: kind,
          },
        },
      },
      null,
      2,
    ) + '\n'
  );
}

function readmeTemplate(kind) {
  return `# \`${kind}\` widget

> Generated by \`npm run widget:new ${kind}\`. Replace this stub before
> shipping.

## What it does

TODO: one paragraph. Is it explanatory or answer-producing? What does
the student manipulate?

## Config

See [\`params.schema.json\`](./params.schema.json). Fields:

- \`label\` *(string, default \`"${kind}"\`)* — TODO.

## Notes

The render function runs **inside the sandboxed iframe** — no captured
closures, no app-bundle imports. See [\`docs/widgets/anatomy.md\`](../../../../docs/widgets/anatomy.md)
for the full SDK reference.
`;
}

function main() {
  const kind = process.argv[2];
  try {
    validateKind(kind);
  } catch (err) {
    console.error(`✗ ${err.message}`);
    console.error('  Usage: npm run widget:new <kind>');
    process.exit(1);
  }
  const ident = kindToIdentifier(kind);

  const dir = join(WIDGETS_DIR, kind);
  if (existsSync(dir)) {
    console.error(`✗ src/widgets/${kind}/ already exists — refusing to overwrite.`);
    process.exit(1);
  }

  const registrySource = readFileSync(REGISTRY_PATH, 'utf8');
  // Defensive: if a previous run left a registry entry without a folder
  // (or the contributor edited the registry by hand) catch it before we
  // produce a broken state.
  if (registrySource.includes(`'${kind}':`) || registrySource.includes(`from './${kind}'`)) {
    console.error(`✗ "${kind}" is already registered in src/widgets/registry.ts — refusing to duplicate.`);
    process.exit(1);
  }

  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.ts'), widgetIndexTemplate(kind, ident));
  writeFileSync(join(dir, 'params.schema.json'), paramsSchemaTemplate(kind));
  writeFileSync(join(dir, 'README.md'), readmeTemplate(kind));

  const patched = patchRegistry(registrySource, kind, ident);
  writeFileSync(REGISTRY_PATH, patched);

  console.log(`✓ Created src/widgets/${kind}/{index.ts, params.schema.json, README.md}`);
  console.log(`✓ Registered "${kind}" in src/widgets/registry.ts (import \`${ident}\`)`);
  console.log('');
  console.log('Next steps:');
  console.log(`  1. Fill in the render function in src/widgets/${kind}/index.ts.`);
  console.log(`  2. Replace the stub fields in params.schema.json with real config.`);
  console.log(`  3. Add "${kind}" to KNOWN_WIDGET_KINDS in`);
  console.log('     backend/openshiksha/apps/core/widgets.py so the writable serializer accepts it.');
  console.log('  4. npm run type-check && npm test');
}

// Only auto-run when invoked directly; tests import the pure helpers from
// `create-widget-utils.mjs` so this executable can keep its shebang.
if (process.argv[1] && process.argv[1].endsWith('create-widget.mjs')) {
  main();
}
