# Generated by Django 4.2.18 on 2026-01-05 07:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("admin", "School Admin"),
                            ("open_student", "Open Student"),
                        ],
                        help_text="The type of user account",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Grade/Standard for students (1-12)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="Contact phone number", max_length=15),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Children managed by this parent",
                        related_name="parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the educational board (e.g., CBSE, ICSE)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "boards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Grade number (1-12)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "standards",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the subject", max_length=255, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name of the school", max_length=255),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "focus_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the focus rooms feature is enabled",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, help_text="Whether SMS notifications are enabled"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        help_text="The educational board/curriculum this school follows",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="core.board",
                    ),
                ),
            ],
            options={
                "db_table": "schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.CharField(help_text="Division name (e.g., A, B, C)", max_length=50),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="Academic year (e.g., 2024-25)", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="The teacher managing this classroom",
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The school this classroom belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="core.school",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        help_text="The grade/standard of this classroom",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classrooms",
                        to="core.standard",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Students enrolled in this classroom",
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        related_name="classes_enrolled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classrooms",
                "ordering": ["school", "standard", "division"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the chapter/topic", max_length=255),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order within subject"),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "standard",
                    models.ForeignKey(
                        help_text="The grade/standard this chapter is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="core.standard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this chapter belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "chapters",
                "ordering": ["subject", "standard", "order"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="The school this user belongs to (null for open students)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.school",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["board", "is_active"], name="schools_board_i_d9b28a_idx"),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["school", "academic_year", "is_active"],
                name="classrooms_school__dfa677_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("school", "standard", "division", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("subject", "standard", "name")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "school"], name="users_role_81975d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
    ]
