# Generated by Django 4.2.18 on 2026-03-28 02:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                            ("multi_select", "Multi Select"),
                            ("numeric", "Numeric Answer"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Difficulty level: 1=easiest, 5=hardest",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="core.chapter"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = OpenShiksha shared question bank",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.school",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="core.standard"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="core.subject"
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("skill", "Skill"),
                            ("difficulty", "Difficulty"),
                            ("special", "Special"),
                        ],
                        default="concept",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "question_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subject_rooms", to="core.classroom"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        related_name="subject_rooms_enrolled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="subject_rooms", to="core.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_rooms_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subject_rooms",
            },
        ),
        migrations.CreateModel(
            name="QuestionSubpart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveIntegerField(help_text="Order within question (0-indexed)")),
                (
                    "correct_answer",
                    models.JSONField(
                        default=dict,
                        help_text='Answer data: e.g. {"type": "mcq", "answer": 2} or {"type": "fill_blank", "answer": "42"}',
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subparts", to="core.question"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="subparts", to="core.questiontag")),
            ],
            options={
                "db_table": "question_subparts",
                "ordering": ["index"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="questions", to="core.questiontag"),
        ),
        migrations.CreateModel(
            name="ProblemSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Series number within same chapter (disambiguates multiple problem sets per chapter)",
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Estimated completion time in minutes", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="problem_sets", to="core.chapter"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_sets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("questions", models.ManyToManyField(blank=True, related_name="problem_sets", to="core.question")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = shared OpenShiksha problem set",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_sets",
                        to="core.school",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="problem_sets", to="core.standard"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="problem_sets", to="core.subject"
                    ),
                ),
            ],
            options={
                "db_table": "problem_sets",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                (
                    "number",
                    models.PositiveIntegerField(
                        default=1, help_text="Disambiguates if same problem set is assigned twice to same room"
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(
                        blank=True,
                        help_text="Average submission score (0.0–1.0), cached after grading",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Fraction of students who have submitted (0.0–1.0)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="core.problemset"
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="core.subjectroom"
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Fraction of marks obtained (0.0–1.0). Null until graded.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "completion",
                    models.FloatField(
                        default=0.0,
                        help_text="Fraction of questions attempted (0.0–1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text='Student answers keyed by subpart ID: {"42": 3, "43": "photosynthesis"}'
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When student clicked Submit. Null = still in progress.", null=True
                    ),
                ),
                ("is_revised", models.BooleanField(default=False, help_text="Whether this is a revised attempt")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="core.assignment"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "indexes": [models.Index(fields=["student", "submitted_at"], name="submissions_student_6bcf5e_idx")],
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="subjectroom",
            index=models.Index(fields=["classroom", "is_active"], name="subject_roo_classro_ed5806_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subjectroom",
            unique_together={("classroom", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="questionsubpart",
            unique_together={("question", "index")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["chapter", "is_active"], name="questions_chapter_7bd7e3_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["school", "standard", "subject"], name="questions_school__48cf35_idx"),
        ),
        migrations.AddIndex(
            model_name="problemset",
            index=models.Index(fields=["chapter", "is_active"], name="problem_set_chapter_75450f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="problemset",
            unique_together={("school", "standard", "subject", "chapter", "number")},
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["subject_room", "due_at"], name="assignments_subject_3bb5a4_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["assigned_at"], name="assignments_assigne_7fbca4_idx"),
        ),
    ]
