# Generated by Django 4.2.22 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_question_questiontag_subjectroom_questionsubpart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="question_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="LaTeX or plain text for the question prompt. Use $...$ for inline math.",
            ),
        ),
        migrations.AddField(
            model_name="questionsubpart",
            name="options",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='MCQ choices: [{"key": "A", "text": "..."}, ...]. Null for non-MCQ types.',
            ),
        ),
    ]
