# Generated by Django 4.2.18 on 2026-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_question_text_and_options_to_questionsubpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="variable_constraints",
            field=models.JSONField(
                blank=True,
                help_text='Variable definitions for token substitution. e.g. {"a": {"min": 1, "max": 9, "integer": true}}. Tokens {{a}} in question_text/options are replaced per student.',
                null=True,
            ),
        ),
    ]
