# Generated by Django 4.2.30 on 2026-05-23 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_questionsubpart_variable_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="is_remedial",
            field=models.BooleanField(
                default=False, help_text="Auto-created by grader for students scoring below the remedial threshold"
            ),
        ),
        migrations.AddField(
            model_name="problemset",
            name="source_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The original assignment this remedial was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remedial_problem_sets",
                to="core.assignment",
            ),
        ),
        migrations.CreateModel(
            name="StudentStreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_streaks",
            },
        ),
    ]
