# Generated by Django 4.2.30 on 2026-05-24 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_student_streak_and_remedial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this student sees this assignment (used for per-student remedials). Null = class-wide.",
                limit_choices_to={"role__in": ["student", "open_student"]},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
