# Generated by Django 4.2.30 on 2026-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_student_streak_and_remedial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional image shown above the question text (teacher-provided URL)",
                max_length=2000,
            ),
        ),
    ]
