# Generated by Django 4.2.30 on 2026-05-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_assignment_target_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentstreak",
            name="streak_grace_used",
            field=models.BooleanField(
                default=False,
                help_text="True if the student has already used their grace day for the current streak run.",
            ),
        ),
    ]
