# Generated by Django 4.2.30 on 2026-05-26 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_streak_grace_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomInviteCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="6-character uppercase alphanumeric code (e.g. 'ABC123')",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invite_code", to="core.classroom"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classroom_invite_codes",
            },
        ),
    ]
