# Generated by Django 4.2.30 on 2026-05-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_classroom_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroominvitecode",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invite_codes", to="core.classroom"
            ),
        ),
    ]
