# Generated by Django 4.2.30 on 2026-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fix_classroom_invite_code_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="hint_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Progressive hint shown to struggling students. Populated by Cabinet import or teacher.",
            ),
        ),
        migrations.AddField(
            model_name="questionsubpart",
            name="solution_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Step-by-step worked solution (plain text or KaTeX). Populated by Cabinet import or LLM generation.",
            ),
        ),
    ]
