# Generated by Django 4.2.30 on 2026-05-29 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_questionsubpart_solution_hint_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_reminders_opt_out",
            field=models.BooleanField(
                default=False, help_text="If True, the student will not receive assignment due-date reminder emails."
            ),
        ),
        migrations.CreateModel(
            name="AssignmentReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="core.assignment"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["student", "open_student"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_reminders",
                "indexes": [models.Index(fields=["assignment", "student"], name="assignment__assignm_038a93_idx")],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
