# Generated by Django 4.2.30 on 2026-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cabinet_tag_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="stem_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional shared stem rendered once above the subpart list. Cabinet compound questions share a leading paragraph; the importer lifts it here so each subpart's question_text holds only the per-part prompt. Hand-authored questions leave this blank.",
            ),
        ),
    ]
