# Generated by Django 4.2.30 on 2026-06-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_question_stem_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("matching", "Matching"),
                    ("multi_select", "Multi Select"),
                    ("numeric", "Numeric Answer"),
                    ("short_answer", "Short Answer"),
                ],
                default="mcq",
                max_length=20,
            ),
        ),
    ]
