# Generated by Django 4.2.30 on 2026-06-02 06:51

from django.db import migrations, models

_VALID_TYPES = {"mcq", "fill_blank", "matching", "multi_select", "numeric", "short_answer"}


def backfill_subpart_type(apps, schema_editor):
    """Backfill subpart_type from correct_answer['type'] (idempotent: only fills
    blanks) and recompute each Question.question_type — unanimous subpart type →
    that type, mixed → 'compound'. Never clobbers hand-authored rows."""
    Question = apps.get_model("core", "Question")
    for question in Question.objects.prefetch_related("subparts").iterator(chunk_size=500):
        subparts = list(question.subparts.all())
        if not subparts:
            continue
        seen = set()
        for sp in subparts:
            if not sp.subpart_type:
                ca_type = (sp.correct_answer or {}).get("type")
                sp.subpart_type = ca_type if ca_type in _VALID_TYPES else question.question_type
                sp.save(update_fields=["subpart_type"])
            seen.add(sp.subpart_type)
        seen.discard("")
        if len(seen) == 1:
            summary = next(iter(seen))
        elif len(seen) > 1:
            summary = "compound"
        else:
            summary = question.question_type
        if summary and summary != question.question_type:
            question.question_type = summary
            question.save(update_fields=["question_type"])


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op: subpart_type column is dropped by the AddField reverse,
    and question_type values remain valid choices (no data corruption)."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="subpart_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mcq", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("matching", "Matching"),
                    ("multi_select", "Multi Select"),
                    ("numeric", "Numeric Answer"),
                    ("short_answer", "Short Answer"),
                    ("compound", "Compound (mixed subpart types)"),
                ],
                default="",
                help_text="Per-subpart answer type (mcq / numeric / fill_blank / …). Cabinet stored type per subpart; the modern flat Question.question_type lost it. The grader and the student widget dispatch on this, falling back to the parent Question.question_type when blank (hand-authored rows).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("matching", "Matching"),
                    ("multi_select", "Multi Select"),
                    ("numeric", "Numeric Answer"),
                    ("short_answer", "Short Answer"),
                    ("compound", "Compound (mixed subpart types)"),
                ],
                default="mcq",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_subpart_type, noop_reverse),
    ]
