# Generated by Django 4.2.30 on 2026-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_questionsubpart_subpart_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="interactive_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Raw authored widget HTML (may contain <script>). SECURITY: stored raw on purpose — NEVER render this into the app DOM or via dangerouslySetInnerHTML. It is delivered ONLY to a sandboxed <iframe sandbox="allow-scripts"> (no allow-same-origin) so the script cannot reach app cookies/storage/DOM. {{var}} tokens are substituted per student by the serializer; image tokens are resolved to absolute URLs at import.',
            ),
        ),
        migrations.AddField(
            model_name="questionsubpart",
            name="is_interactive",
            field=models.BooleanField(
                default=False,
                help_text="True when this subpart carries an authored interactive widget (embedded <script>/event handlers). The widget HTML lives in interactive_html and is rendered ONLY inside a sandboxed iframe (M7-11). question_text holds a safe, script-free fallback.",
            ),
        ),
    ]
