# Generated by Django 4.2.30 on 2026-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_questionsubpart_interactive_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubpart",
            name="widget_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-widget config validated against the kind's params schema. May contain {{var}} tokens substituted per student by the serializer (IW-3b).",
            ),
        ),
        migrations.AddField(
            model_name="questionsubpart",
            name="widget_kind",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Registry key of an interactive widget (e.g. 'thermo-piston'). Blank = no widget. The kind-based path is the going-forward Widgets Framework contract and supersedes the legacy interactive_html escape hatch (kept for backwards-compat until IW-7 deprecates it).",
                max_length=64,
            ),
        ),
    ]
