# Generated by Django 4.2.30 on 2026-06-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_questionsubpart_widget_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Display name of the widget in the teacher gallery.", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional one-paragraph blurb for the gallery card."
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("personal", "Personal"), ("school", "School"), ("pending_review", "Pending review")],
                        default="personal",
                        help_text="Gallery visibility — see TeacherWidgetVisibility for the state machine.",
                        max_length=20,
                    ),
                ),
                (
                    "scene_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Scene-schema version this widget was authored against. A future Studio runtime uses this to migrate older scenes on read.",
                    ),
                ),
                (
                    "scene",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pure-data Studio composition: {primitives: [...], bindings: [...], formulas: [...]}. Interpreted by the runtime — never eval'd.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher who composed this widget.",
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_widgets_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning school (null for personal widgets authored by an open / unaffiliated teacher).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_widgets",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_widgets",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["school", "visibility"], name="teacher_wid_school__711da4_idx"),
                    models.Index(fields=["created_by", "updated_at"], name="teacher_wid_created_9c33bd_idx"),
                ],
            },
        ),
    ]
