# Generated by Django 4.2.30 on 2026-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_teacherwidget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsubpart",
            name="interactive_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="DEPRECATED (IW-7) — raw authored widget HTML, kept as a read-only legacy surface until the migration command moves its content into widget_kind='custom-html' + widget_config={'html': <this>}. New authoring MUST use widget_kind + widget_config; this column will be dropped once the legacy thermo row has been migrated. SECURITY invariants unchanged while present: stored raw, NEVER rendered into the app DOM, delivered ONLY to a sandboxed <iframe sandbox=\"allow-scripts\"> (no allow-same-origin).",
            ),
        ),
        migrations.AlterField(
            model_name="questionsubpart",
            name="is_interactive",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED (IW-7) — paired with interactive_html below. The going-forward signal that a subpart carries a widget is widget_kind being non-blank; this flag is kept only so the legacy thermo question keeps rendering until the migration command stamps it with widget_kind='custom-html'. Do not set on new rows.",
            ),
        ),
        migrations.AlterField(
            model_name="questionsubpart",
            name="widget_kind",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Registry key of an interactive widget (e.g. 'thermo-piston', 'custom-html'). Blank = no widget. The kind-based path is the ONE going-forward Widgets Framework contract — the legacy interactive_html escape hatch above is deprecated in favour of widget_kind='custom-html' + widget_config={'html': ...} (IW-7).",
                max_length=64,
            ),
        ),
    ]
