# Generated by Django 4.2.30 on 2026-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_questionsubpart_interactive_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, help_text="When set, the assignment no longer accepts submissions.", null=True
            ),
        ),
    ]
