# Generated by Django 4.2.30 on 2026-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_assignment_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assigned_content",
            field=models.JSONField(
                blank=True,
                help_text="Frozen copy of the problem set's questions at assign time. Source of truth for grading and rendering this assignment — editing the live ProblemSet/Question/Subpart afterwards leaves this snapshot untouched. See apps.core.snapshots.build_assignment_snapshot.",
                null=True,
            ),
        ),
    ]
