# Generated by Django 4.2.30 on 2026-06-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_backfill_assigned_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSnapshotHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.JSONField(help_text="The snapshot that was replaced (immutable).")),
                ("replaced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_history",
                        to="core.assignment",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who triggered the re-sync that displaced this snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_resyncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_snapshot_history",
                "ordering": ["-replaced_at"],
                "indexes": [models.Index(fields=["assignment", "-replaced_at"], name="assignment__assignm_529277_idx")],
            },
        ),
    ]
