# Generated by Django 4.2.30 on 2026-06-09 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_assignment_snapshot_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assigned_content",
            field=models.JSONField(
                blank=True,
                help_text="Frozen copy of the problem set's questions at assign time. Source of truth for grading and rendering this assignment — editing the live ProblemSet/Question/Subpart afterwards leaves this snapshot untouched. See apps.core.snapshots.build_assignment_snapshot. AIV-7: kept for backward compatibility; the canonical content source is now ``problem_set_version`` below. New writers populate both fields so readers can still fall back when the FK is null.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProblemSetVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="1-based ordinal within the parent set, assigned at creation time."
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="sha256 over the canonical (sort_keys) JSON of the questions block. Drives dedup.",
                        max_length=64,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="Frozen snapshot dict — the same shape build_assignment_snapshot() returns."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher whose action minted this version (assigned the set, or re-synced an assignment). Null for backfilled rows.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_set_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="core.problemset"
                    ),
                ),
            ],
            options={
                "db_table": "problem_set_versions",
                "ordering": ["problem_set_id", "version_number"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="problem_set_version",
            field=models.ForeignKey(
                blank=True,
                help_text="AIV-7: the deduplicated, immutable content version this assignment pins. Preferred source of truth; falls back to ``assigned_content`` when null (legacy rows the backfill couldn't reach).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="core.problemsetversion",
            ),
        ),
        migrations.AddIndex(
            model_name="problemsetversion",
            index=models.Index(fields=["problem_set", "-version_number"], name="problem_set_problem_afd374_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="problemsetversion",
            unique_together={("problem_set", "content_hash")},
        ),
    ]
