# Generated by Django 4.2.30 on 2026-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_backfill_problem_set_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi")],
                default="en",
                help_text="Preferred UI/content language; follows the user across devices.",
                max_length=8,
            ),
        ),
    ]
