# Generated by Django 4.2.30 on 2026-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("mr", "Marathi")],
                default="en",
                help_text="Preferred UI/content language; follows the user across devices.",
                max_length=8,
            ),
        ),
    ]
