# Generated by Django 4.2.30 on 2026-06-18 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_user_preferred_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "endpoint",
                    models.URLField(
                        help_text="Push service endpoint URL (unique per browser).", max_length=512, unique=True
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(
                        help_text="Client public key (keys.p256dh) for payload encryption.", max_length=255
                    ),
                ),
                (
                    "auth",
                    models.CharField(
                        help_text="Client auth secret (keys.auth) for payload encryption.", max_length=255
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent at subscribe time (diagnostics only).", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this browser subscription.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_subscriptions",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "created_at"], name="push_subscr_user_id_5f4007_idx")],
            },
        ),
    ]
