# Generated by Django 4.2.30 on 2026-06-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")], default="success", max_length=16
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(blank=True, help_text="Compressed dump size in bytes.", null=True),
                ),
                (
                    "object_key",
                    models.CharField(blank=True, help_text="S3 object key of the uploaded dump.", max_length=512),
                ),
            ],
            options={
                "db_table": "backup_runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
