# Generated by Django 6.0.6 on 2026-07-07 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_backuprun"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human label for the pack (from the pack's optional `name`), shown in the review queue.",
                        max_length=200,
                    ),
                ),
                (
                    "pack_hash",
                    models.CharField(
                        db_index=True,
                        help_text="CP-1 canonical-JSON SHA-256 of the pack. Keys import idempotency and the superseded transition.",
                        max_length=64,
                    ),
                ),
                (
                    "provenance",
                    models.JSONField(
                        default=dict,
                        help_text="The pack's provenance block (author, license, source, contact) — attribution for materialized questions.",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="The full CP-1-validated content pack, retained so approval can materialize its questions.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reviewer note recorded on the last transition (e.g. the rejection reason).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the submission was last reviewed (set on any transition out of PENDING/into a terminal state).",
                        null=True,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who last transitioned this submission (approve/reject/re-open).",
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_submissions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_submissions",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["state", "created_at"], name="content_sub_state_c1a85b_idx")],
            },
        ),
    ]
