# Generated by Django 4.2.30 on 2026-05-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_fix_classroom_invite_code_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Video title", max_length=255)),
                ("embed_url", models.URLField(help_text="Embeddable video URL (e.g. YouTube embed link)")),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Optional description of the video"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order within the chapter (ascending)"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Hide without deleting when False")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="The chapter this video supports",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="core.chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher/admin who added this video",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lodge_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
