# Generated by Django 4.2.30 on 2026-05-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_fix_classroom_invite_code_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(help_text="The announcement text")),
                ("is_active", models.BooleanField(default=True, help_text="Hide without deleting when False")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The teacher who posted this announcement",
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_room",
                    models.ForeignKey(
                        help_text="The subject room this announcement targets",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="core.subjectroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["subject_room", "is_active"], name="announcemen_subject_455704_idx")],
            },
        ),
    ]
