apiVersion: v1
kind: ConfigMap
metadata:
  name: openshiksha-config
data:
  ALLOWED_HOSTS: qa.openshiksha.org,backend
  CORS_ALLOWED_ORIGINS: https://qa.openshiksha.org
  CSRF_TRUSTED_ORIGINS: https://qa.openshiksha.org
